#!/usr/bin/env python3
"""
Usage:
    ./gen_sdc.py <module>           # writes flat_modules/<mod>/<mod>.sdc
    ./gen_sdc.py all                # regenerate every module
    ./gen_sdc.py <module> --stdout  # print instead of writing

"""

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
MODULES_DIR = REPO_ROOT / "flat_modules"
# SDCs live next to synth outputs. Match syn_script.sh default; honor SYN_WORK_ROOT.
SDC_OUT_ROOT = Path(os.environ.get("SYN_WORK_ROOT", REPO_ROOT / "genus"))

# Defaults
CLK_PERIOD_NS = 2.0
CLK_DUTY_HIGH_NS = 0.9
IN_DELAY_MAX_NS = 0.2
IN_DELAY_MIN_NS = -0.2
OUT_DELAY_MAX_NS = 0.5
OUT_DELAY_MIN_NS = -0.2
LOAD_PF = 0.050  # 50 fF
MAX_CAP_PF = 0.010  # 10 fF
CLK_UNCERT_SETUP = 0.03
CLK_UNCERT_HOLD = 0.10
MAX_TRANSITION_NS = 0.12

# Ports that get special treatment.
CLK_PORT = "clk"
RSTN_PORT = "rst_n"


PORT_RE = re.compile(
    r"\b(input|output|inout)\b"
    r"(?:\s+(?:logic|wire|reg|bit))?"
    r"(?:\s+(?:signed|unsigned))?"
    r"(?:\s*\[[^\]]+\])?"
    r"\s*([A-Za-z_][A-Za-z0-9_]*)"
)


def parse_ports(top_sv: Path):
    """Return (inputs, outputs) as lists of port names, in declaration order."""
    text = top_sv.read_text()

    header_end = text.find(");")
    if header_end == -1:
        raise RuntimeError(f"Could not find end of port list in {top_sv}")
    header = text[:header_end]

    inputs, outputs = [], []
    for direction, name in PORT_RE.findall(header):
        if direction == "input":
            inputs.append(name)
        elif direction == "output":
            outputs.append(name)
    return inputs, outputs


def build_sdc(module: str, inputs, outputs) -> str:
    if CLK_PORT not in inputs:
        raise RuntimeError(f"{module}: no '{CLK_PORT}' input found")

    data_inputs = [p for p in inputs if p not in (CLK_PORT, RSTN_PORT)]
    has_rstn = RSTN_PORT in inputs
    in_list = " ".join(data_inputs)
    out_list = " ".join(outputs)

    lines = []
    w = lines.append

    w(f"# Auto-generated by gen_sdc.py for {module}.")
    w(f"# Edit gen_sdc.py to change defaults, then regenerate.")
    w("")
    w(
        f"create_clock -name {CLK_PORT} -period {CLK_PERIOD_NS} "
        f"-waveform {{ 0 {CLK_DUTY_HIGH_NS} }} [get_ports {CLK_PORT}]"
    )
    w("")
    w(
        "# ------------------------- Input constraints ----------------------------------"
    )
    w(
        f"set_input_delay  -clock {CLK_PORT} -max {IN_DELAY_MAX_NS} "
        f"[get_ports {{{in_list}}}]"
    )
    w(
        f"set_input_delay  -clock {CLK_PORT} -min {IN_DELAY_MIN_NS} "
        f"[get_ports {{{in_list}}}]"
    )
    w("")
    w(
        "# ------------------------- Output constraints ---------------------------------"
    )
    w(
        f"set_output_delay -clock {CLK_PORT} -max {OUT_DELAY_MAX_NS} "
        f"[get_ports {{{out_list}}}]"
    )
    w(
        f"set_output_delay -clock {CLK_PORT} -min {OUT_DELAY_MIN_NS} "
        f"[get_ports {{{out_list}}}]"
    )
    w("")
    if has_rstn:
        w(f"set_false_path -from [get_ports [list {RSTN_PORT}]]")
    w(f"set_load {LOAD_PF} [get_ports {{{out_list}}}]")
    w(f"set_max_capacitance {MAX_CAP_PF} [get_ports {{{in_list}}}]")
    w("")
    w(f"set_clock_uncertainty -setup {CLK_UNCERT_SETUP} [get_clocks {{{CLK_PORT}}}]")
    w(f"set_clock_uncertainty -hold  {CLK_UNCERT_HOLD} [get_clocks {{{CLK_PORT}}}]")
    w("")
    w(f"set_max_transition {MAX_TRANSITION_NS} [current_design]")
    w("")
    return "\n".join(lines)


def gen_for_module(module: str, stdout: bool) -> bool:
    mod_dir = MODULES_DIR / module
    top_sv = mod_dir / f"{module}_top.sv"
    if not top_sv.is_file():
        print(f"ERROR: {top_sv} not found", file=sys.stderr)
        return False

    inputs, outputs = parse_ports(top_sv)
    sdc = build_sdc(module, inputs, outputs)

    if stdout:
        print(sdc)
    else:
        out_dir = SDC_OUT_ROOT / module
        out_dir.mkdir(parents=True, exist_ok=True)
        out = out_dir / f"{module}.sdc"
        out.write_text(sdc)
        print(f"wrote {out}")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("target", help="module name, or 'all'")
    ap.add_argument(
        "--stdout",
        action="store_true",
        help="print SDC to stdout instead of writing file",
    )
    args = ap.parse_args()

    if args.target == "all":
        ok = True
        for d in sorted(MODULES_DIR.iterdir()):
            if not d.is_dir():
                continue
            if not (d / f"{d.name}_top.sv").is_file():
                continue
            ok &= gen_for_module(d.name, args.stdout)
        sys.exit(0 if ok else 1)
    else:
        sys.exit(0 if gen_for_module(args.target, args.stdout) else 1)


if __name__ == "__main__":
    main()
